kind: pipeline
type: docker
name: test

steps:
#   - name: test1
#     image: leofigy/nanobell:latest
#     environment:
#       GITHUB_TOKEN:
#         from_secret: GITHUB_TOKEN
  - name: test1
    image: debian:stable-slim
    commands:
      - echo -e '{{#success build.status}}\n Build #{{build.number}} of `{{repo.name}}` succeeded.\n📝 Commit by {{commit.author}} on `{{commit.branch}}`:\n```\n{{commit.message}}\n```\n{{ build.link }}\n{{else}}\n Build #{{build.number}} of `{{repo.name}}` failed.\n\n Commit by {{commit.author}} on `{{commit.branch}}`:\n```\n{{commit.message}}\n```\n\n{{ build.link }}\n{{/success}}'| tee /bellator_message/bellator_message.tpl
    volumes:
      - /bellator_message:/bellator_message
  - name: send telegram notification
    image: appleboy/drone-telegram
    when:
      status: [ success, failure ]
    settings:
      token:
        from_secret: telegram_token
      to:
        from_secret: telegram_to
      message_file: bellator_message/bellator_message.tpl
    volumes:
      - /bellator_message:/bellator_message

trigger:
  branch:
  - master
  - drone-testing
  event:
  - pull_request
