kind: pipeline
type: docker
name: test

steps:
#   - name: test1
#     image: leofigy/nanobell:latest
#     environment:
#       GITHUB_TOKEN:
#         from_secret: GITHUB_TOKEN
  - name: test1
    image: ubuntu
    commands:
      - echo hello | tee bellator_message.tpl
  - name: send telegram notification
    image: appleboy/drone-telegram
    when:
      status: [ success, failure ]
    settings:
      token:
        from_secret: telegram_token
      to:
        from_secret: telegram_to
      message_file: bellator_message/bellator_message.tpl

trigger:
  branch:
  - master
  - drone-testing
  event:
  - pull_request
