kind: pipeline
type: docker
name: test

steps:
#   - name: test1
#     image: leofigy/nanobell:latest
#     environment:
#       GITHUB_TOKEN:
#         from_secret: GITHUB_TOKEN
  - name: test1
    image: debian:stable-slim
    commands:
      - echo '  {{#success build.status}}
        😂 Build #{{build.number}} of `{{repo.name}}` succeeded.


        📝 Commit by {{commit.author}} on `{{commit.branch}}`:

        ```
        {{commit.message}}
        ```


        🌐 {{ build.link }}
        {{else}}
        ❌ Build #{{build.number}} of `{{repo.name}}` failed.


        📝 Commit by {{commit.author}} on `{{commit.branch}}`:

        ```
        {{commit.message}}
        ```


        🌐 {{ build.link }}
        {{/success}}' | tee /bellator_message/bellator_message.tpl
    volumes:
      - /bellator_message:/bellator_message
  - name: send telegram notification
    image: appleboy/drone-telegram
    when:
      status: [ success, failure ]
    settings:
      token:
        from_secret: telegram_token
      to:
        from_secret: telegram_to
      message_file: bellator_message/bellator_message.tpl
    volumes:
      - /bellator_message:/bellator_message

trigger:
  branch:
  - master
  - drone-testing
  event:
  - pull_request
